//go:build cgo && c2go

#include "linkedGeo.c"

// Wrapper for bboxFromLinkedGeoLoop (generated by polygonAlgos.h macro)
void bboxFromLinkedGeoLoopC(const LinkedGeoLoop *loop, BBox *bbox) {
    bboxFromLinkedGeoLoop(loop, bbox);
}

// Wrapper for pointInsideLinkedGeoLoop (generated by polygonAlgos.h macro)
bool pointInsideLinkedGeoLoopC(const LinkedGeoLoop *loop, const BBox *bbox, const LatLng *coord) {
    return pointInsideLinkedGeoLoop(loop, bbox, coord);
}

// Wrapper for isClockwiseLinkedGeoLoop (generated by polygonAlgos.h macro)
bool isClockwiseLinkedGeoLoopC(const LinkedGeoLoop *loop) {
    return isClockwiseLinkedGeoLoop(loop);
}

// Wrapper for addNewLinkedPolygon
LinkedGeoPolygon* addNewLinkedPolygonC(LinkedGeoPolygon *polygon) {
    return addNewLinkedPolygon(polygon);
}

