//go:build cgo && c2go

#include "linkedGeo.c"

// Wrapper for bboxFromLinkedGeoLoop (generated by polygonAlgos.h macro)
void bboxFromLinkedGeoLoopC(const LinkedGeoLoop *loop, BBox *bbox) {
    bboxFromLinkedGeoLoop(loop, bbox);
}

// Wrapper for pointInsideLinkedGeoLoop (generated by polygonAlgos.h macro)
bool pointInsideLinkedGeoLoopC(const LinkedGeoLoop *loop, const BBox *bbox, const LatLng *coord) {
    return pointInsideLinkedGeoLoop(loop, bbox, coord);
}

// Wrapper for isClockwiseLinkedGeoLoop (generated by polygonAlgos.h macro)
bool isClockwiseLinkedGeoLoopC(const LinkedGeoLoop *loop) {
    return isClockwiseLinkedGeoLoop(loop);
}

// Wrapper for addNewLinkedPolygon
LinkedGeoPolygon* addNewLinkedPolygonC(LinkedGeoPolygon *polygon) {
    return addNewLinkedPolygon(polygon);
}

// Wrapper for addLinkedLoop
LinkedGeoLoop* addLinkedLoopC(LinkedGeoPolygon *polygon, LinkedGeoLoop *loop) {
    return addLinkedLoop(polygon, loop);
}

// Wrapper for addNewLinkedLoop
LinkedGeoLoop* addNewLinkedLoopC(LinkedGeoPolygon *polygon) {
    return addNewLinkedLoop(polygon);
}

// Wrapper for addLinkedCoord
LinkedLatLng* addLinkedCoordC(LinkedGeoLoop *loop, const LatLng *vertex) {
    return addLinkedCoord(loop, vertex);
}

// Wrapper for countLinkedPolygons
int countLinkedPolygonsC(LinkedGeoPolygon *polygon) {
    return countLinkedPolygons(polygon);
}

// Wrapper for countContainers
int countContainersC(const LinkedGeoLoop *loop,
                     const LinkedGeoPolygon **polygons,
                     const BBox **bboxes, int polygonCount) {
    return countContainers(loop, polygons, bboxes, polygonCount);
}

// Wrapper for findDeepestContainer
const LinkedGeoPolygon* findDeepestContainerC(const LinkedGeoPolygon **polygons,
                                               const BBox **bboxes, int polygonCount) {
    return findDeepestContainer(polygons, bboxes, polygonCount);
}

