//go:build cgo && c2go

#include "linkedGeo.c"

// Wrapper for bboxFromLinkedGeoLoop (generated by polygonAlgos.h macro)
void bboxFromLinkedGeoLoopC(const LinkedGeoLoop *loop, BBox *bbox) {
    bboxFromLinkedGeoLoop(loop, bbox);
}

