package c2go

// PentagonDirectionFaces is a table entry for direction-to-face mapping for pentagons.
// Ported from H3 C: vertex.c
type PentagonDirectionFaces struct {
	baseCell int32
	faces    [5]int32
}

// DIRECTION_INDEX_OFFSET is used to convert directions to pentagon face indices.
// Ported from H3 C: vertex.c
const DIRECTION_INDEX_OFFSET = 2

// INVALID_VERTEX_NUM represents an invalid vertex number.
// Ported from H3 C: vertex.h
const INVALID_VERTEX_NUM = -1

// pentagonDirectionFaces is a table of direction-to-face mapping for each pentagon.
// Note that faces are in directional order, starting at J_AXES_DIGIT.
// This table is generated by the generatePentagonDirectionFaces script.
// Ported from H3 C: vertex.c::pentagonDirectionFaces
var pentagonDirectionFaces = [NUM_PENTAGONS]PentagonDirectionFaces{
	{4, [5]int32{4, 0, 2, 1, 3}},
	{14, [5]int32{6, 11, 2, 7, 1}},
	{24, [5]int32{5, 10, 1, 6, 0}},
	{38, [5]int32{7, 12, 3, 8, 2}},
	{49, [5]int32{9, 14, 0, 5, 4}},
	{58, [5]int32{8, 13, 4, 9, 3}},
	{63, [5]int32{11, 6, 15, 10, 16}},
	{72, [5]int32{12, 7, 16, 11, 17}},
	{83, [5]int32{10, 5, 19, 14, 15}},
	{97, [5]int32{13, 8, 17, 12, 18}},
	{107, [5]int32{14, 9, 18, 13, 19}},
	{117, [5]int32{15, 19, 17, 18, 16}},
}

// directionToVertexNumHex maps hexagon directions to vertex numbers (same face).
// Note that we don't use direction 0 (center).
// Ported from H3 C: vertex.c::directionToVertexNumHex
var directionToVertexNumHex = [NUM_DIGITS]int32{
	int32(INVALID_DIGIT), 3, 1, 2, 5, 4, 0,
}

// directionToVertexNumPent maps pentagon directions to vertex numbers (same face).
// Note that we don't use directions 0 (center) or 1 (deleted K axis).
// Ported from H3 C: vertex.c::directionToVertexNumPent
var directionToVertexNumPent = [NUM_DIGITS]int32{
	int32(INVALID_DIGIT), int32(INVALID_DIGIT), 1, 2, 4, 3, 0,
}

// vertexNumToDirectionHex maps hexagon vertex numbers to directions (same face).
// Ported from H3 C: vertex.c::vertexNumToDirectionHex
var vertexNumToDirectionHex = [NUM_HEX_VERTS]Direction{
	IJ_AXES_DIGIT, J_AXES_DIGIT, JK_AXES_DIGIT,
	K_AXES_DIGIT, IK_AXES_DIGIT, I_AXES_DIGIT,
}

// vertexNumToDirectionPent maps pentagon vertex numbers to directions (same face).
// Ported from H3 C: vertex.c::vertexNumToDirectionPent
var vertexNumToDirectionPent = [NUM_PENT_VERTS]Direction{
	IJ_AXES_DIGIT, J_AXES_DIGIT, JK_AXES_DIGIT, IK_AXES_DIGIT, I_AXES_DIGIT,
}

// directions in CCW order.
// Ported from H3 C: vertex.c::DIRECTIONS
var directions = [NUM_HEX_VERTS]Direction{
	J_AXES_DIGIT, JK_AXES_DIGIT, K_AXES_DIGIT,
	IK_AXES_DIGIT, I_AXES_DIGIT, IJ_AXES_DIGIT,
}

// revNeighborDirectionsHex reverse direction from neighbor in each direction,
// given as an index into DIRECTIONS to facilitate rotation.
// Ported from H3 C: vertex.c::revNeighborDirectionsHex
var revNeighborDirectionsHex = [NUM_DIGITS]int32{
	int32(INVALID_DIGIT), 5, 3, 4, 1, 0, 2,
}
